steps:
# Diagnostic step to list workspace contents
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'ls -la /workspace']
  id: 'List Workspace Contents'

# --- Backend Build ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/tmontgo/task-list-backend/task-list-backend:latest', '.']
  dir: 'backend'
  id: 'Build Backend Image'

# --- Frontend Build ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest', '.']
  dir: 'frontend'
  id: 'Build Frontend Image'

# --- Backend Push ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/tmontgo/task-list-backend/task-list-backend:latest']
  id: 'Push Backend Image'
  waitFor: ['Build Backend Image']

# --- Frontend Push ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest']
  id: 'Push Frontend Image'
  waitFor: ['Build Frontend Image']

# --- Database Initialization ---
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'backend/db/init_tasks_table.sql', 'gs://tmontgo-sql-init/init_tasks_table.sql']
  id: 'Upload SQL to GCS'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud sql import sql task-list-db gs://tmontgo-sql-init/init_tasks_table.sql --database=tasks --user=task_app_user || echo "Database import failed, continuing..."
  id: 'Initialize Database'
  waitFor: ['Upload SQL to GCS']
  env:
    - 'CLOUDSDK_CORE_PROJECT=tmontgo'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'

# --- Backend Deploy ---
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'task-list-backend'
    - '--image'
    - 'us-central1-docker.pkg.dev/tmontgo/task-list-backend/task-list-backend:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - 'tmontgo:us-central1:task-list-db'
    - '--set-env-vars'
    - 'DB_USER=task_app_user,DB_PASSWORD=newpassword123,DB_NAME=tasks,CLOUD_SQL_CONNECTION_NAME=tmontgo:us-central1:task-list-db,NODE_ENV=production'
  id: 'Deploy Backend to Cloud Run'
  waitFor: ['Push Backend Image', 'Initialize Database']

# --- Frontend Deploy ---
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'task-list-frontend'
    - '--image'
    - 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
  id: 'Deploy Frontend to Cloud Run'
  waitFor: ['Push Frontend Image']


options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
images:
- 'us-central1-docker.pkg.dev/tmontgo/task-list-backend/task-list-backend:latest'
- 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest'