steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest', '.']
    dir: 'frontend'
    id: 'Build Frontend Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest']
    id: 'Push Frontend Image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'task-list-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/tmontgo/task-list-frontend/task-list-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'Deploy Frontend to Cloud Run'
