version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env  # Use the root .env file

  db:
    image: mysql:8
    env_file:
      - .env  # Use the root .env file
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_tasks_table.sql:/docker-entrypoint-initdb.d/init_tasks_table.sql  # Mount the SQL file for initialization

volumes:
  db_data:
