version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4000" # Frontend connects to the backend on localhost in development

backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  ports:
    - "4000:4000"
  depends_on:
    - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    env_file:
      - .env  # Root .env file for MySQL variables
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./db:/docker-entrypoint-initdb.d  # Mount the db directory for initialization scripts

volumes:
  db_data:
